# Generated by Django 4.2 on 2025-02-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='contact_number',
            new_name='phone',
        ),
    ]
